# Generated by Django 3.2.13 on 2022-07-04 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_ingredient_recette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='recette',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='blog.recette'),
        ),
    ]
