# Generated by Django 3.2.13 on 2022-07-05 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_membre_mdp'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='crecette',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crecette', to='blog.recette'),
        ),
    ]
