# Generated by Django 3.2.13 on 2022-07-06 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_commentaire_crecette'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='crecette',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='idrecette',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arecette', to='blog.recette'),
        ),
    ]
