# Generated by Django 3.2.13 on 2022-07-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_idrecette_commentaire_arecette'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='mdp',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
    ]
